# Generated by Django 5.2.17 on 2026-08-26 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cinemas", "0001_initial"),
        ("movies", "0002_movie_poster_url_alter_movie_poster"),
    ]

    operations = [
        migrations.CreateModel(
            name="Showtime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("ticket_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "booking_mode",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned Seating"),
                            ("general", "General Admission"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showtimes",
                        to="movies.movie",
                    ),
                ),
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showtimes",
                        to="cinemas.screen",
                    ),
                ),
            ],
        ),
    ]
