# Generated by Django 5.2.17 on 2026-08-31 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_seat_unique_seat_per_screen'),
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showtimes', to='cinemas.screen'),
        ),
    ]
