from datetime import date

from django.core.management.base import BaseCommand
from django.db import transaction

from movies.models import Movie


class Command(BaseCommand):
    help = "Add 30 new development movies to CineFlow."

    @transaction.atomic
    def handle(self, *args, **options):
        self.stdout.write(self.style.WARNING("Adding 30 new CineFlow movies..."))

        movies = [
            {
                "slug": "titanic",
                "title": "Titanic",
                "description": "A young woman from an aristocratic family falls in love with an artist aboard the ill-fated RMS Titanic.",
                "poster_url": "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=kVrqfYjkTdQ",
                "duration": 195,
                "release_date": date(1997, 12, 19),
                "age_rating": "PG-13",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "jurassic-park",
                "title": "Jurassic Park",
                "description": "Scientists are invited to a remote island where genetically recreated dinosaurs have escaped their enclosures.",
                "poster_url": "https://image.tmdb.org/t/p/w500/63viWuPfYQjRYLSZSZNq7dglJP5.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=lc0UehYemtnZR07cKXGg8vQ5Y1V",
                "duration": 127,
                "release_date": date(1993, 6, 11),
                "age_rating": "PG-13",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "the-departed",
                "title": "The Departed",
                "description": "An undercover police officer and a mole in the state police try to identify each other while infiltrating a Boston crime syndicate.",
                "poster_url": "https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=ioX7dBlmI6Jk7f6Qx6Zk9v1cL2A",
                "duration": 151,
                "release_date": date(2006, 10, 6),
                "age_rating": "R",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "whiplash",
                "title": "Whiplash",
                "description": "A young jazz drummer enters an intense conservatory program led by an instructor whose methods push him to the limit.",
                "poster_url": "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=7d_jQycdQGo",
                "duration": 107,
                "release_date": date(2014, 10, 10),
                "age_rating": "R",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "la-la-land",
                "title": "La La Land",
                "description": "A jazz pianist and an aspiring actress fall in love while pursuing their dreams in Los Angeles.",
                "poster_url": "https://img.youtube.com/vi/0pdqf4P9MB8/hqdefault.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=0pdqf4P9MB8",
                "duration": 128,
                "release_date": date(2016, 12, 9),
                "age_rating": "PG-13",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "mad-max-fury-road",
                "title": "Mad Max: Fury Road",
                "description": "In a ruined wasteland, Max joins Furiosa and a group of rebels fleeing a tyrannical ruler.",
                "poster_url": "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=hEJnMQG9ev8",
                "duration": 120,
                "release_date": date(2015, 5, 15),
                "age_rating": "R",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "blade-runner-2049",
                "title": "Blade Runner 2049",
                "description": "A young blade runner uncovers a long-buried secret that leads him to track down a former officer.",
                "poster_url": "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=gCcx85zbxz4",
                "duration": 164,
                "release_date": date(2017, 10, 6),
                "age_rating": "R",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "the-social-network",
                "title": "The Social Network",
                "description": "A student creates a revolutionary social network and faces lawsuits and betrayals as it rapidly expands.",
                "poster_url": "https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=lB95KLmpLR4",
                "duration": 120,
                "release_date": date(2010, 10, 1),
                "age_rating": "PG-13",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "arrival",
                "title": "Arrival",
                "description": "A linguist works with the military to communicate with mysterious visitors from another world.",
                "poster_url": "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=tFMo3UJ4B4g",
                "duration": 116,
                "release_date": date(2016, 11, 11),
                "age_rating": "PG-13",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "logan",
                "title": "Logan",
                "description": "In the near future, an aging Logan cares for an ailing Professor X while protecting a young mutant.",
                "poster_url": "https://image.tmdb.org/t/p/w500/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=Div0iP65aZo",
                "duration": 137,
                "release_date": date(2017, 3, 3),
                "age_rating": "R",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "coco",
                "title": "Coco",
                "description": "A young musician enters the Land of the Dead to discover his family history and fulfill his dream of music.",
                "poster_url": "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=Rvr68u6k5sI",
                "duration": 105,
                "release_date": date(2017, 11, 22),
                "age_rating": "PG",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "wall-e",
                "title": "WALL-E",
                "description": "A small waste-collecting robot discovers a new purpose when he meets an advanced probe sent to Earth.",
                "poster_url": "https://image.tmdb.org/t/p/w500/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=8-_9n5DtKOc",
                "duration": 98,
                "release_date": date(2008, 6, 27),
                "age_rating": "G",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "up",
                "title": "Up",
                "description": "An elderly widower ties balloons to his house and travels to South America with an unexpected stowaway.",
                "poster_url": "https://placehold.co/500x750/111827/FFFFFF/png?text=Up",
                "trailer_url": "https://www.youtube.com/watch?v=pkqzFUhGPJg",
                "duration": 96,
                "release_date": date(2009, 5, 29),
                "age_rating": "PG",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "toy-story",
                "title": "Toy Story",
                "description": "A cowboy doll feels threatened when a new space-ranger toy becomes the favorite of their owner.",
                "poster_url": "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=CxwTLktovTU",
                "duration": 81,
                "release_date": date(1995, 11, 22),
                "age_rating": "G",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "finding-nemo",
                "title": "Finding Nemo",
                "description": "A timid clownfish crosses the ocean to find his son after the young fish is captured by divers.",
                "poster_url": "https://image.tmdb.org/t/p/w500/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=wZdpNglLcqE",
                "duration": 100,
                "release_date": date(2003, 5, 30),
                "age_rating": "G",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "ratatouille",
                "title": "Ratatouille",
                "description": "A talented rat who dreams of becoming a chef forms an unlikely partnership with a young kitchen worker.",
                "poster_url": "https://img.youtube.com/vi/NgsQ8mVkN8w/hqdefault.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=NgsQ8mVkN8w",
                "duration": 111,
                "release_date": date(2007, 6, 29),
                "age_rating": "G",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "the-incredibles",
                "title": "The Incredibles",
                "description": "A family of undercover superheroes is forced back into action to save the world from a dangerous enemy.",
                "poster_url": "https://placehold.co/500x750/111827/FFFFFF/png?text=The%20Incredibles",
                "trailer_url": "https://www.youtube.com/watch?v=eZbzbCkC0E4",
                "duration": 115,
                "release_date": date(2004, 11, 5),
                "age_rating": "PG",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "moana",
                "title": "Moana",
                "description": "A courageous teenager sails across the ocean to save her island and restore the heart of a goddess.",
                "poster_url": "https://img.youtube.com/vi/LKFuXETZUsI/hqdefault.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=LKFuXETZUsI",
                "duration": 107,
                "release_date": date(2016, 11, 23),
                "age_rating": "PG",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "frozen",
                "title": "Frozen",
                "description": "A fearless young woman sets out to find her sister, whose powers have trapped their kingdom in eternal winter.",
                "poster_url": "https://image.tmdb.org/t/p/w500/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=TbQm5doF_Uc",
                "duration": 102,
                "release_date": date(2013, 11, 27),
                "age_rating": "PG",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "the-prestige",
                "title": "The Prestige",
                "description": "Two rival magicians engage in a bitter contest that consumes their lives and leads to dangerous secrets.",
                "poster_url": "https://img.youtube.com/vi/o4gHCmTQDVI/hqdefault.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=o4gHCmTQDVI",
                "duration": 130,
                "release_date": date(2006, 10, 20),
                "age_rating": "PG-13",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "gone-girl",
                "title": "Gone Girl",
                "description": "A man becomes the center of intense media attention when his wife disappears on their anniversary.",
                "poster_url": "https://img.youtube.com/vi/2-_-1nJf8Vg/hqdefault.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=2-_-1nJf8Vg",
                "duration": 149,
                "release_date": date(2014, 10, 3),
                "age_rating": "R",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "the-grand-budapest-hotel",
                "title": "The Grand Budapest Hotel",
                "description": "A legendary concierge and his young protégé become entangled in a theft and a family inheritance dispute.",
                "poster_url": "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=1Fg5iWmQjwk",
                "duration": 100,
                "release_date": date(2014, 3, 28),
                "age_rating": "R",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "her",
                "title": "Her",
                "description": "A lonely writer develops an unlikely relationship with an operating system designed to meet his every need.",
                "poster_url": "https://placehold.co/500x750/111827/FFFFFF/png?text=Her",
                "trailer_url": "https://www.youtube.com/watch?v=WzV6mXIOVl4",
                "duration": 126,
                "release_date": date(2013, 12, 18),
                "age_rating": "R",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "the-truman-show",
                "title": "The Truman Show",
                "description": "A man discovers that his entire life is actually a television show broadcast to millions of viewers.",
                "poster_url": "https://img.youtube.com/vi/dlnmQbPGuls/hqdefault.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=dlnmQbPGuls",
                "duration": 103,
                "release_date": date(1998, 6, 5),
                "age_rating": "PG",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "the-green-mile",
                "title": "The Green Mile",
                "description": "A prison guard encounters an inmate with a mysterious gift that changes everyone around him.",
                "poster_url": "https://img.youtube.com/vi/Ki4haFrqSrw/hqdefault.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=Ki4haFrqSrw",
                "duration": 189,
                "release_date": date(1999, 12, 10),
                "age_rating": "R",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "saving-private-ryan",
                "title": "Saving Private Ryan",
                "description": "A group of soldiers crosses war-torn France to bring a missing paratrooper home.",
                "poster_url": "https://img.youtube.com/vi/9CiW_DgxCnQ/hqdefault.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=9CiW_DgxCnQ",
                "duration": 169,
                "release_date": date(1998, 7, 24),
                "age_rating": "R",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "the-pianist",
                "title": "The Pianist",
                "description": "A Jewish pianist struggles to survive the destruction of Warsaw during the Second World War.",
                "poster_url": "https://img.youtube.com/vi/BFwGqLa_oAo/hqdefault.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=BFwGqLa_oAo",
                "duration": 150,
                "release_date": date(2002, 9, 25),
                "age_rating": "R",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "life-of-pi",
                "title": "Life of Pi",
                "description": "A young man survives a shipwreck and shares a lifeboat with a Bengal tiger.",
                "poster_url": "https://img.youtube.com/vi/j9Hjrs6WQ8M/hqdefault.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=j9Hjrs6WQ8M",
                "duration": 127,
                "release_date": date(2012, 11, 21),
                "age_rating": "PG",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "the-martian",
                "title": "The Martian",
                "description": "An astronaut stranded on Mars uses ingenuity and science to survive while a rescue mission is planned.",
                "poster_url": "https://img.youtube.com/vi/ej3ioOneTy8/hqdefault.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=ej3ioOneTy8",
                "duration": 144,
                "release_date": date(2015, 10, 2),
                "age_rating": "PG-13",
                "status": Movie.Status.NOW_SHOWING,
            },
            {
                "slug": "knives-out",
                "title": "Knives Out",
                "description": "A detective investigates the death of a wealthy novelist while every member of the family becomes a suspect.",
                "poster_url": "https://img.youtube.com/vi/qGqiHJTsRkQ/hqdefault.jpg",
                "trailer_url": "https://www.youtube.com/watch?v=qGqiHJTsRkQ",
                "duration": 130,
                "release_date": date(2019, 11, 27),
                "age_rating": "PG-13",
                "status": Movie.Status.NOW_SHOWING,
            },
        ]

        created_count = 0
        existing_count = 0

        for movie_data in movies:
            movie = Movie.objects.filter(slug=movie_data["slug"]).first()
            if movie:
                existing_count += 1
                self.stdout.write(self.style.WARNING(f"Already exists: {movie.title}"))
                continue
            movie = Movie.objects.create(**movie_data)
            created_count += 1
            self.stdout.write(self.style.SUCCESS(f"Created: {movie.title}"))

        self.stdout.write(self.style.SUCCESS("Movie operation completed."))
        self.stdout.write(f"Movies created: {created_count}")
        self.stdout.write(f"Movies already existed: {existing_count}")
