# Generated by Django 5.2.17 on 2026-08-29 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_hold_expires_at_alter_booking_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingseat',
            options={'ordering': ['seat']},
        ),
        migrations.RemoveConstraint(
            model_name='bookingseat',
            name='unique_seat_per_showtime',
        ),
    ]
