# Generated by Django 5.2.17 on 2026-08-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookingseat_options_and_more'),
        ('cinemas', '0002_seat_unique_seat_per_screen'),
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.UniqueConstraint(fields=('showtime', 'seat'), name='unique_seat_per_showtime'),
        ),
    ]
