# Generated by Django 5.2.17 on 2026-09-05 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_refund'),
        ('cinemas', '0002_seat_unique_seat_per_screen'),
        ('showtimes', '0002_alter_showtime_screen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='bookings.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_reservations', to='cinemas.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_reservations', to='showtimes.showtime')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('showtime', 'seat'), name='unique_active_seat_per_showtime')],
            },
        ),
    ]
