# Generated by Django 5.2.17 on 2026-09-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_seatreservation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookingseat',
            name='unique_seat_per_showtime',
        ),
    ]
