# Generated by Django 5.2.17 on 2026-09-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_bookingseat_unique_seat_per_showtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='paystack_transaction',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
