# Generated by Django 5.2.17 on 2026-08-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("poster", models.ImageField(upload_to="movies/posters/")),
                ("trailer_url", models.URLField(blank=True)),
                ("duration", models.PositiveIntegerField()),
                ("release_date", models.DateField()),
                ("age_rating", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("coming_soon", "Coming Soon"),
                            ("now_showing", "Now Showing"),
                            ("ended", "Ended"),
                        ],
                        default="coming_soon",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
