# Generated by Django 5.2.17 on 2026-08-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="poster_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="movies/posters/"),
        ),
    ]
